<a href="https://colab.research.google.com/github/2303A51111/B3_PFDS_1111/blob/main/LAB_03_AUG_14th.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A=[[3,4],[7,4],[8,2]]
B=[[13,4],[43,7],[32,9]]
C=np.array(A)
D=np.array(B)
print("Matrix 1\n",C)
print("Matrix 2\n",D)

Add = np.add(A,B)

print("Addition Result\n",Add)

Sub= np.subtract(A,B)

print("Subtraction Result\n",Sub)

Matrix 1
 [[3 4]
 [7 4]
 [8 2]]
Matrix 2
 [[13  4]
 [43  7]
 [32  9]]
Addition Result
 [[16  8]
 [50 11]
 [40 11]]
Subtraction Result
 [[-10   0]
 [-36  -3]
 [-24  -7]]
